articles/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^python/$',views.python_list, name='p_list'),
    url(r'^blog/$',views.blog_list, name='pb_list'),
    url(r'^write/$',views.writeblog, name='write'),
    url(r'^(?P<id>\d+)/$',views.full_article, name='full'),
    url(r'^update/(?P<id>\d+)/$',views.update_view, name='update'),
    url(r'^delete/(?P<id>\d+)/$',views.delete_view, name='delete'),
]

knowart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('myapp.urls')),
    url(r'^articles/',include('articles.urls', namespace='article')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.home, name='home'),
    url(r'^signup/$',views.signup, name='signup'),
    url(r'^login/$',views.login_view, name='login'),
    url(r'^logout/$',views.logout_view, name='logout'),
    url(r'^showprofile/$',views.showProfile, name='showprofile'),
    url(r'^deleteprofile/(?P<id>\d+)/$',views.deleteProfile, name='deleteprofile'),
    url(r'^editprofile/$',views.editProfile, name='editprofile'),
    url(r'^change-password/$',views.changepass, name='changepass'),
]

articles/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Types(models.Model):
    types = models.CharField(max_length=20)

    def __str__(self):
        return self.types


class Articles(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Types, default=True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, default=True, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now, blank=True)
    body = models.TextField()
    thumb = models.ImageField(blank=True, upload_to='post')

    def __str__(self):
        return self.title

    def short(self):
        return self.body[:75] + '...'

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dp = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return self.user.username

articles/forms.py
from .models import Articles
from django import forms


class Writeform(forms.ModelForm):
    thumb = forms.ImageField(label='Image')

    class Meta:
        model = Articles
        fields = (
            'title',
            'body',
            'thumb',
            'category'
        )

myapp/forms.py
from django import forms
from django.contrib.auth.models import User  # built-in user model
from django.contrib.auth.forms import UserCreationForm  # in-built form
from .models import Profile


class Registrationform(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:  # information about the model
        model = User  # this model is referring to User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2',)  # listing the names of the fields you want to use


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['dp']

articles/views.py
from django.shortcuts import (render,
                              redirect,
                              get_object_or_404
                              )
from .models import Articles
from django.contrib.auth.decorators import login_required
from . import forms


def python_list(request):
    articles = Articles.objects.filter(category=1)
    return render(request, 'articles/articles.html', {'articles': articles})


def blog_list(request):
    articles = Articles.objects.filter(category=2)
    return render(request, 'articles/articles.html', {'articles': articles})


def full_article(request, id):
    # article = Articles.objects.get(id=id)
    article = get_object_or_404(Articles, id=id)
    return render(request, 'articles/fullarticle.html', {'article': article})


@login_required()
def writeblog(request):
    if request.method == 'POST':
        form = forms.Writeform(request.POST or None, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('home')
    else:
        form = forms.Writeform()
    return render(request, 'articles/writeblog.html', {'form': form})


@login_required()
def update_view(request, id):
    article = get_object_or_404(Articles, id=id)
    if request.method == 'POST':
        form = forms.Writeform(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return render(request, 'articles/fullarticle.html', {'article': article})
    form = forms.Writeform(instance=article)
    context = {'form': form,
               'article': article}
    return render(request, 'articles/updateblog.html', context)


def delete_view(request, id):
    Articles.objects.get(id=id).delete()
    return redirect('home')

myapp/views.py
from django.shortcuts import render, redirect
from .forms import Registrationform, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import (login,
                                 logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from articles.models import Articles
from django.contrib.auth.models import User


def home(request):
    articles = Articles.objects.all()
    context = {'articles': articles}
    return render(request, 'account/homepage.html', context)


def signup(request):
    if request.method == 'POST':
        form = Registrationform(request.POST or None)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = Registrationform()
    return render(request, 'account/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST or None)  # request.POST is not the first parameter
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'account/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


@login_required()
def editProfile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('showprofile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user)
        context = {'u_form': u_form,
                   'p_form': p_form}
    return render(request, 'account/editprofile.html', context)


def showProfile(request):
    return render(request, 'account/showProfile.html')

def deleteProfile(request,id):
    User.objects.get(id=id).delete()
    return redirect('home')

@login_required()
def changepass(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST or None, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('showprofile')
        else:
            return redirect('changepass')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'account/passwordchange.html', {'form': form})

articles/templates/articles/articles.html
{% extends 'account/homepage.html' %}
{% block body %}
<body>
<br>
<div class="container">
    <div class="row">
        {% for article in articles %}
        <div class="col-md-12 col-sm-6 col-lg-6">
            <div class="card" style="width: 19rem;">
                <div class="card-body">
                    <a href="{% url 'article:full' id=article.id %}">
                        {% if article.thumb %}
                        <img class="card-img-top" src="{{article.thumb.url}}" alt="img" width="280" height="180">
                        {% else %}
                        <img class="card-img-top" src="media/default_blog_pic.jpg" alt="img" width="280" height="180">
                        {% endif %}
                        <h6 class="card-title">
                            <a href="{% url 'article:full' id=article.id %}">{{article.title}}</a>
                        </h6>
                        <p class="card-text">{{article.short}}</p>
                        <hr>
                        <small class="text-muted">{{article.author}},</small>
                        <small class="text-muted">{{article.date|date:"F d, Y"}}</small>
                    </a>
                </div>
            </div>
            <br>
        </div>
        {% endfor %}
    </div>
</div>

</body>
{% endblock body %}

articles/templates/articles/fullarticle.html
{% extends 'account/homepage.html' %}
{% block body %}
<style>
    .container{
    padding-right:150px;
    padding-left:150px;
    margin-top: 15px;
    }
</style>
<div>
    <br>
    <div class="container">
        <h2 style="font-family:Georgia;"><b>{{article.title}}</b></h2><br>
        <h6 class="text-muted"><a style="text-decoration: none;" class="text-muted" href="#">{{article.author}}</a>, {{article.date|date:"F d, Y"}}</h6>
        <hr>
        {% if article.thumb %}
        <center><img src="{{article.thumb.url}}" width="550" height="350"></center><br>
        {% endif %}
        <p style="font-family:Arial;font-size:large;">{{article.body}}</p>
        {% if user.is_superuser %}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'article:update' id=article.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'article:delete' id=article.id %}">Delete</a>
          </div>
        {% endif %}
    </div>
</div>
{% endblock %}

articles/templates/articles/updateblog.html
{% extends 'account/homepage.html' %}
{% load crispy_forms_tags %}
{% block body %}
<style>
    .container{
    padding-right:300px;
    padding-left:300px;
    margin-top: 15px;
    }
</style>
<div>
    <form method="POST" action="{% url 'article:update' id=article.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="well">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Update</legend></fieldset>
        <table>
            {{form|crispy}}
        </table>
                <br><button type="submit" class="btn btn-primary">update</button>
            </div>
        </div>
    </form>
</div>
{% endblock body %}

articles/templates/articles/writeblog.html
{% extends 'account/homepage.html' %}
{% load crispy_forms_tags %}
{% block body %}
<style>
    .container{
    padding-right:300px;
    padding-left:300px;
    margin-top: 15px;
    }
</style>
<div>
    <form method="POST" action="{% url 'article:write' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="well">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Write</legend></fieldset>
        <table>
            {{form|crispy}}
        </table>
                <br><button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>
{% endblock body %}